// <auto-generated />
namespace Urfu.Its.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddChiarToProgram : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddChiarToProgram));
        
        string IMigrationMetadata.Id
        {
            get { return "201509101042292_AddChiarToProgram"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
