// <auto-generated />
namespace Urfu.Its.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MinorRequirments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MinorRequirments));
        
        string IMigrationMetadata.Id
        {
            get { return "201607251522316_MinorRequirments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
