// <auto-generated />
namespace Urfu.Its.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SectionFK_Add_IncrementID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SectionFK_Add_IncrementID));
        
        string IMigrationMetadata.Id
        {
            get { return "201612151019434_SectionFK_Add_IncrementID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
