// <auto-generated />
namespace Urfu.Its.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CompetencesTable_AddContent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CompetencesTable_AddContent));
        
        string IMigrationMetadata.Id
        {
            get { return "201711300922275_CompetencesTable_AddContent"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
