// <auto-generated />
namespace Urfu.Its.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DWP_Remove_Upopstatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DWP_Remove_Upopstatus));
        
        string IMigrationMetadata.Id
        {
            get { return "201806081342246_DWP_Remove_Upopstatus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
