// <auto-generated />
namespace Urfu.Its.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RequisiteOrderFGOS_Date2OnlyDateFormat : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RequisiteOrderFGOS_Date2OnlyDateFormat));
        
        string IMigrationMetadata.Id
        {
            get { return "201801190727430_RequisiteOrderFGOS_Date2OnlyDateFormat"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
