// <auto-generated />
namespace Urfu.Its.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RemoveStandardFieldFromBasicCharacteristicOPTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RemoveStandardFieldFromBasicCharacteristicOPTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202001140912486_RemoveStandardFieldFromBasicCharacteristicOPTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
